---
title: "Reaction Paper zu „what can we learn from twin studies? A comprehensive evaluation of the equal environment assumption“ von Felson (2014) "
#author: "Edna Grewers"
editor: visual
---

[*CN: Zwillingsstudien, Genetik.*]{style="color:darkgreen"} [published: 02 Jul 2024 by Edna Grewers]{style="color:gray"}

Zwillingsstudien werden eingesetzt, um zu untersuchen inwiefern Genetik menschliche Merkmale und Verhalten beeinflusst. Anders als bei genomweiten Studien, bei denen sich einzelne Genotypen oder SNPs angeschaut werden, untersucht man die Unterschiede von eineiigen oder monozygoten Zwillingen (MZ), die sich 100% ihrer DNA teilen, und zweieiigen oder dizygoten Zwillingen (DZ), die sich im Schnitt nur 50% ihrer DNA teilen, vergleichbar mit anderen Geschwistern. Das Design gibt damit nicht nur Aufschluss über einzelne Geninformationen (Genotypen), sondern auch über ihre Ausprägungen (Phänotypen), da epigenetische Anlagen mitvererbt werden können. Dabei wird davon ausgegangen, dass Zwillinge die gleiche Umwelt haben, d.h. gleichalt sind, bei den gleichen Eltern groß werden, den gleichen sozialökonomischen Hintergrund haben, etc. und Unterschiede im Phänotyp primär durch genetische Variation oder andere nicht Umwelt bedingte Einflüsse verursacht sind. Diese Annahme heißt in der Literatur equal environment assumption (EEA).

Felson diskutiert, die Kritik an EAA und dass man die Validität und Reliabilität verbessern könne, indem man einerseits Daten umfassender erhebt und andererseits inhaltsreicher auswertet. Er nimmt für die Datenauswertung ein simples Modell, was die Ursache eines Traits in Heritabilität (h2) und gemeinsame Umwelt (c2) aufteilt. Heritabilität meint die Erblichkeit, also welche Gene von den Eltern weitergegeben werden und gemeinsame Umwelt meint, was für gleiche und gemeinsame Erfahrungen die Zwillinge gemacht haben. Felson untersucht bereits erhobene Daten aus dem National Merit Scholar Qualifikation Test (NMSQT) zu Intelligenz und Persönlichkeit, wertet die Daten aber neu aus. Statt Berichte der Eltern, inwiefern die Zwillinge gleiche Erfahrungen gemacht haben, nimmt er Selbstauskünfte der Zwillinge stärker in den Fokus. Durch diese angeblich reliablere Messung wird ein kleiner Effekt von gemeinsamer Umwelt auf Heritabilität gefunden (r = 0.09). Auch Untersuchungen aus Studien zu Adoptivkindern und getrennt aufwachsenden Zwillingen zeigen ähnliche Befunde. Alle drei Designs könnten ähnliche Biases in der Erfassung der Daten haben, womit laut Felson die wahre Heritabilität der untersuchten Merkmale überschätzt werden könnte. Erfasst man die Daten reliabel und geht davon aus, dass EEA stimmt, dann würde man keine großen Unterschiede erwarten, wenn man für gemeinsame Umwelt kontrolliert. Felsons Datenauswertung fand eine signifikante Reduktion von h2 bei Neurotizismus, und größere nicht signifikante Reduktionen bei ca. der Hälfte der untersuchten Merkmale. Da diese Konfundierung keine Muster aufzeigt, schließt Felson daraus, dass es sich wahrscheinlich um zufällige Fluktuation handelt und die Ergebnisse von EEA valide sind, wenn auch mitunter mit moderaten Verletzungen.

Zum Schluss betont er, dass sich Gene ohne sozialen Kontext nicht entfalten können (phenotypic bottleneck), dennoch scheinen Gene für viele Phänotypen eine größere Vorhersagekraft zu haben als die Sozialisierung durch die Eltern alleine, nicht nur für physiologische Merkmale, sondern auch für psychologische und soziologische.

Dafür, dass die Studie versucht genauere Datenauswertung vorzunehmen, war ich etwas überrascht, dass ein simples Modell zur Auswertung genutzt wurde und nicht etwa das von Brocke (Brocke 2006), indem nicht nur Erbe und Umwelt getrennt voneinander, sondern auch ihre Interaktion berücksichtigt wird. Dass Kinder reaktiv gefördert werden oder sich aktiv ihre eigene Umgebung suchen und gestalten, scheint mir ein wichtiger Faktor zu sein, um nicht nur den Einfluss der Genetik, sondern auch den der Umwelt und ihre Verhältnis zueinander korrekt wiedergeben zu können.

In der Konklusion betont Felson, dass es sozialen Kontext braucht, damit sich Gene entfalten können, schließt dann aber, dass seine Funde nicht auf sozialen Einfluss zurückzuführen seien, sondern auf zufällige Fluktuation. Sein Schluss, dass es unwahrscheinlich sei, dass bspw. Neurotizismus und Gewissenhaftigkeit mehr von sozialer Umwelt beeinflusst werden als andere Persönlichkeitsmerkmale, scheint mir nicht ausreichend belegt. Ich würde aus den Daten schließen, dass weitere Erhebungen nötig sind, um das zu beantworten. Persönlichkeitsmerkmale wie die Big Five basieren auf einem lexikalischen Ansatz (Schulz 2023), sie sind demnach keine angeborenen Konzepte, sondern eine Gruppierung korrelierender Merkmale. Korrelationen müssen dabei nicht durch gleiche Ursachen zustande kommen, um als bedeutsam zu gelten und um damit Vorhersagen machen zu können.

Nach lesen des Papers scheinen weder EEA, noch genomweite Studien die perfekte Art zu sein, um den Zusammenhäng zwischen Genetik, Umwelteinflüssen und Verhalten oder Merkmalen zu untersuchen. Beide haben Vor- aber auch Nachteile. Man sollte also entweder beide nutzen, oder weiteren Designs erarbeiten. Statt mit Zwillingen könnte man auch mit statistischen Zwillingen die Zusammenhänge zwischen Genetik und Verhalten untersuchen. Dabei könnte man Informationen aus genomweiten Studien nutzen, um statistische Zwillinge zu bilden. Auch hier sollten sich sowohl die Genotypen als auch die Umwelt angeschaut werden. Diese untersucht man dann ähnlich wie bei klassischen Zwillingsstudien bzw. wie Zwillinge, die getrennt aufgewachsen sind. Vorteile könnten repräsentativere Stichproben sein. Nachteile wären, dass man neben der genetischen Information noch Fragebogenerhebungen machen müsste.

### Literatur

Brocke, B., Müller, J., Strobel, A. (2006). *Verhaltensgenetische Ansätze und Theorien der Persönlichkeitsforschung, Kapitel 25 Verhaltensgenetik* (pp. 355-361). Hogrefe

Felson, J. (2014). What can we learn from twin studies? A comprehensive evaluation of the equal environments assumption. *Social Science Research, 43*, 184–199. <https://doi.org/10.1016/j.ssresearch.2013.10.004>{style="color:#3498db"}

Schulze, R. (2023, May 3). Big Five Persönlichkeitsfaktoren. *Spektrum Akademischer Verlag*. <https://www.spektrum.de/lexikon/psychologie/big-five-persoenlichkeitsfaktoren/2360>{style="color:#3498db"}
