---
title: "Dino intro"
abstract-title: "content note"
abstract: "Dinos"
author: "Edna Grewers"
date: today
date-format: "D MMM YYYY"
editor: visual
---
### warum Dinos?

Ich erinnere mich daran, wie ich mit 2-3 auf dem Schreibtisch meines Bruders saß, während er in der Schule war. Er hatte ein Bild eines T-Rex gemalt, der von Fliegern angegriffen wurde. Vielleicht war es auch Godzilla, aber meine Mutter meinte, ich soll nicht ins Zimmer meines Bruders, wenn er nicht da ist. Zu der Zeit lief auch die Serie „die Dinos“. Ich kann mich nicht mehr daran erinnern, worum es genau ging, nur dass das Baby im Hochsitz saß und den Vater mit der Bratpfanne geschlagen hat (mein Highlight). 
Ich hatte lange nichts mehr über Dinos gehört, aber in letzter Zeit taucht das Thema immer wieder auf. Damals war ich zu jung bzw. fand „die älteren Jungs“, die alles über Dinos wussten interessanter als die Dinos selbst. Jetzt bin ich der Nerd und habe viele wissenschaftlichen Studien zum Aussehen, Lebensweise von Dinos und ihrem soziokulturellem Einfluss ihrer Interpretationen und Projektionen gefunden (vermutlich geschrieben von „den älteren Jungs“, die jetzt in der Wissenschaft arbeiten). 
Vor allem die vielen Studien, die diskutieren, nicht nur was wir wissen über Fossilien; sondern eben, was wir überhaupt wissen können – und was nicht – interessieren mich. Welche Funktionen haben die Geschichten, die wir uns über Dinos erzählen? Woher kommt das Interesse? Und was hat das mit Kolonialismus zu tun (natürlich)?
