---
title: "Wechseljahre"
editor: visual
---

# Plan

Ich möchte einen Artikel über Wechseljahre schreiben. Die zweite Pubertät bzw. der Übergang vom Erwachsenenalter zum Alt-sein betrifft alle Menschen, mit und ohne Uterus, egal welches Gender.

## Fragen

Mich interessieren: was Wissen wir über die Wechseljahre bei cis Frauen? Was bei trans Männern, die Testosteron nehmen (wenn Daten vorhanden sind), was bei Menschen, deren Uterus entfernt wurde (mit/ohne hormonelle Behandlung).

Was wissen wir über die Wechseljahre bei cis Männern? Wird das auch Wechseljahre genannt oder hat das einen anderen Begriff? Was wissen wir über die Wechseljahre bei trans Frauen und so ist der Unterschied?

Welchen Einfluss haben (welche) Hormone beim Wechsel vom erwachsen sein zum alt sein, d.h. welche Hormone ändern sich? Welche Hormone beeinflussen während des Wechsels unserer Verhalten, unsere Emotionen und welche körperlichen Auswirkungen machen sich bemerkbar (Blutungen, Erektionsstörungen, Hitzewallungen, etc.).

### mögliche Zusammenhänge recherchieren zu:

-   Suizidrate bei mittelalten Männern und Wechseljahre (beides glaube ich in den 50-60ern).

## Themen
Datenlage zu folgenden Themen rausfinden: 

-   Menstruation und Uterus
-   Menschen mit Hoden
-   was wissen wir über die Wechseljahre bei trans\* Menschen, die Hormone nehmen?
    -   bei Östrogen
    -   bei Testosteron
- was ist mit inter* Menschen?


